import Rank from "../models/rank.model";
import categoryList from "../util/categoryList.util";

export const runRankSeeds = async () => {
  console.log("Seeding Rank table...");

  return await Rank.bulkCreate(
    [
      {
        name: "Novice",
        description:
          "Produce 5 scoresheets each of a different subcategory with at least a 21 score or higher. Of the 5 scoresheets, they shall include a minimum of 4 different BJCP categories",
        priority: 10,
        minScore: 21,
        minSubcats: 5,
        minCats: 4,
        minSlmc: 0,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Apprentice",
        description:
          "Produce 10 scoresheets each of a different subcategory with at least 21 score or higher. Of the 10 scoresheets, they shall include a minimum of 7 different BJCP categories. At least 1 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 20,
        minScore: 21,
        minSubcats: 10,
        minCats: 7,
        minSlmc: 1,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Proficient",
        description:
          "Produce 10 scoresheets each of a different subcategory with at least 30 score or higher. Of the 10 scoresheets, they shall include a minimum of 7 different BJCP categories. At least 2 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 30,
        minScore: 30,
        minSubcats: 10,
        minCats: 7,
        minSlmc: 2,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Recognized",
        description:
          "Produce 15 scoresheets each of a different subcategory with at least 30 score or higher. Of the 15 scoresheets, they shall include a minimum of 10 different BJCP categories. At least 3 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 40,
        minScore: 30,
        minSubcats: 15,
        minCats: 10,
        minSlmc: 3,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Distinguished",
        description:
          "Produce 15 scoresheets each of a different subcategory with at least 38 score or higher. Of the 15 scoresheets, they shall include a minimum of 11 different BJCP categories. At least 2 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 50,
        minScore: 38,
        minSubcats: 15,
        minCats: 11,
        minSlmc: 2,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Master",
        description:
          "Produce 20 scoresheets each of a different subcategory with at least 38 score or higher. Of the 20 scoresheets, they shall include a minimum of 15 different BJCP categories. At least 4 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 60,
        minScore: 38,
        minSubcats: 20,
        minCats: 15,
        minSlmc: 4,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master I",
        description:
          "Produce 10 scoresheets each of a different subcategory with at least 43 score or higher. Of the 10 scoresheets, they shall include a minimum of 5 different BJCP categories. At least 2 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 70,
        minScore: 43,
        minSubcats: 10,
        minCats: 5,
        minSlmc: 2,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master II",
        description:
          "Produce 15 scoresheets each of a different subcategory with at least 43 score or higher. Of the 15 scoresheets, they shall include a minimum of 7 different BJCP categories. At least 4 of the scoresheets shall be a Lager, Mead or Cider",
        priority: 80,
        minScore: 43,
        minSubcats: 15,
        minCats: 7,
        minSlmc: 4,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master III",
        description:
          "Produce 20 scoresheets each of a different subcategory with at least 43 score or higher. Of the 20 scoresheets, they shall include a minimum of 9 different BJCP categories. At least 5 of the scoresheets shall be a Lager, Mead or Cider",
        priority: 90,
        minScore: 43,
        minSubcats: 20,
        minCats: 9,
        minSlmc: 5,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master IV",
        description:
          "Produce 25 scoresheets each of a different subcategory with at least 43 score or higher. Of the 25 scoresheets, they shall include a minimum of 11 different BJCP categories. At least 6 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 100,
        minScore: 43,
        minSubcats: 25,
        minCats: 11,
        minSlmc: 6,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master V",
        description:
          "Produce 30 scoresheets each of a different subcategory with at least 43 score or higher. Of the 30 scoresheets, they shall include a minimum of 13 different BJCP categories. At least 7 of the scoresheets shall be a Sour, Lager, Mead or Cider",
        priority: 110,
        minScore: 43,
        minSubcats: 30,
        minCats: 13,
        minSlmc: 7,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Grand Master VI",
        description:
          "Produce 35 scoresheets each of a different subcategory with at least 43 score or higher. Of the 35 scoresheets, they shall include a minimum of 15 different BJCP categories. At least 8 of the scoresheets shall be a Sour, Lager, Mead or Cider: including a minimum of 5 lagers, 1 cider, 1 mead, and 1 sour.",
        priority: 120,
        minScore: 43,
        minSubcats: 35,
        minCats: 15,
        minSlmc: 0,
        minLagers: 5,
        minSours: 1,
        minMixedSours: 0,
        minMeads: 1,
        minCiders: 1,
      },
      {
        name: "Grand Master VII",
        description:
          "Produce 40 scoresheets each of a different subcategory with at least 43 score or higher. Of the 40 scoresheets, they shall include a minimum of 17 different BJCP categories. At least 9 of the scoresheets shall be a Sour, Lager, Mead or Cider: including a minimum of 5 lagers, 1 cider, 2 mead, and 1 sour.",
        priority: 130,
        minScore: 43,
        minSubcats: 40,
        minCats: 17,
        minSlmc: 0,
        minLagers: 5,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 2,
        minCiders: 1,
      },
      {
        name: "Grand Master VIII",
        description:
          "Produce 45 scoresheets each of a different subcategory with at least 43 score or higher. Of the 45 scoresheets, they shall include a minimum of 19 different BJCP categories. At least 12 of the scoresheets shall be a Sour, Lager, Mead or Cider: including a minimum of 5 lagers, 2 ciders, 2 meads, and 2 sours. At least one of the sours shall be mixed fermentation.",
        priority: 140,
        minScore: 43,
        minSubcats: 45,
        minCats: 19,
        minSlmc: 0,
        minLagers: 6,
        minSours: 2,
        minMixedSours: 1,
        minMeads: 2,
        minCiders: 2,
      },
      {
        name: "Grand Master IX",
        description:
          "Produce 50 scoresheets each of a different subcategory with at least 43 score or higher. Of the 50 scoresheets, they shall include a minimum of 21 different BJCP categories. At least 14 of the scoresheets shall be a Sour, Lager, Mead or Cider: including a minimum of 6 lagers, 3 ciders, 3 meads, and 2 sours. At least one of the sours shall be mixed fermentation.",
        priority: 150,
        minScore: 43,
        minSubcats: 50,
        minCats: 21,
        minSlmc: 0,
        minLagers: 6,
        minSours: 2,
        minMixedSours: 1,
        minMeads: 3,
        minCiders: 3,
      },
      {
        name: "Grand Master X",
        description:
          "Produce 55 scoresheets each of a different subcategory with at least 43 score or higher. Of the 55 scoresheets, they shall include a minimum of 23 different BJCP categories. At least 16 of the scoresheets shall be a Sour, Lager, Mead or Cider: including a minimum of 7 lagers, 3 ciders, 3 meads, and 3 sours. At least one of the sours shall be mixed fermentation.",
        priority: 160,
        minScore: 43,
        minSubcats: 55,
        minCats: 23,
        minSlmc: 0,
        minLagers: 7,
        minSours: 3,
        minMixedSours: 1,
        minMeads: 3,
        minCiders: 3,
      },
      {
        name: "Legendary Master",
        description:
          "Produce 1 scoresheet of at least 43 score or higher for every category of beer, mead, and Cider",
        priority: 170,
        minScore: 43,
        minSubcats: 0,
        minCats: Object.keys(
          categoryList.reduce((acc, val) => {
            acc[val.cat] = true;
            return acc;
          }, {})
        ).length,
        minSlmc: 0,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
      {
        name: "Supreme Master of Brewing",
        description:
          "Produce 1 scoresheets of at least 43 score or higher for every sub-category of beer, mead, and Cider",
        priority: 180,
        minScore: 43,
        minSubcats: categoryList.length,
        minCats: 0,
        minSlmc: 0,
        minLagers: 0,
        minSours: 0,
        minMixedSours: 0,
        minMeads: 0,
        minCiders: 0,
      },
    ],
    {
      ignoreDuplicates: true,
    }
  );
};
